; Documentation association is captured here, not inferred by plugin traversal.
(function_item (attributes (line_outer_doc_comment)+ @fold @related.documentation))
(function_item (attributes (block_outer_doc_comment) @fold @related.documentation))
((line_comment)+ @fold @related.documentation . (function_item))
((function_item
   (attributes (line_outer_doc_comment)+ @fold @related.documentation)
   body: (block) @related.from)
  (#match? @related.from "\n")
  (#set! tag "deleted-bodies:docstring")
  (#set! tag "summarize:docstring")
  (#set! tag "test-bodies:docstring"))
((function_item
   (attributes (block_outer_doc_comment) @fold @related.documentation)
   body: (block) @related.from)
  (#match? @related.from "\n")
  (#set! tag "deleted-bodies:docstring")
  (#set! tag "summarize:docstring")
  (#set! tag "test-bodies:docstring"))
((line_comment)+ @fold @related.documentation . (function_item body: (block) @related.from)
  (#match? @related.from "\n")
  (#set! tag "deleted-bodies:docstring")
  (#set! tag "summarize:docstring")
  (#set! tag "test-bodies:docstring"))
