; inherits: builtin:core/queries/go/folds.scm, builtin:core/queries/go/docstrings.scm, builtin:shared/queries/go-tests.scm
((function_declaration body: (block "{" @fold.open (statement_list . (labeled_statement (label_name) . (_) @fold.indent) @_first) "}" @fold.close) @fold)
  (#match? @_first "^[A-Za-z_][A-Za-z0-9_]*:\\s*\n")
  (#set! tag "summarize:function"))
((function_declaration body: (block "{" @fold.open (statement_list . (_) @fold.indent) "}" @fold.close) @fold)
  (#not-match? @fold.indent "^[A-Za-z_][A-Za-z0-9_]*:\\s*\n")
  (#set! tag "summarize:function"))
((method_declaration body: (block "{" @fold.open (statement_list . (labeled_statement (label_name) . (_) @fold.indent) @_first) "}" @fold.close) @fold)
  (#match? @_first "^[A-Za-z_][A-Za-z0-9_]*:\\s*\n")
  (#set! tag "summarize:function"))
((method_declaration body: (block "{" @fold.open (statement_list . (_) @fold.indent) "}" @fold.close) @fold)
  (#not-match? @fold.indent "^[A-Za-z_][A-Za-z0-9_]*:\\s*\n")
  (#set! tag "summarize:function"))
