//! A port of GitHub Linguist's `lib/linguist/generated.rb` (MIT; see
//! `linguist/LICENSE`), taken from github-linguist/linguist at commit
//! 16cac170f73c97eb4e4329d66fcb341ef25ef4f0.
//!
//! Linguist asks one question of a file's name and whole content. diffr splits
//! it in two so content is read only when it could matter: [`by_path`] holds
//! every rule that looks at the path alone, [`needs_content`] says whether any
//! content rule's name or extension guard admits the path, and [`by_content`]
//! runs those rules over the file's first [`super::PREFIX_BYTES`].
//!
//! Every rule in `generated?` is ported. Where a rule reads the end of the file
//! (`has_source_map?`, `generated_net_docfile?`, `vcr_cassette?` and the
//! module-closure branch of `compiled_coffeescript?`) it runs only when the
//! prefix is the whole file. `minified_files?` averages line length over the
//! prefix, and `generated_postscript?` searches the prefix for its markers.
//! Rules that index a line Linguist would find missing (Ruby's `nil`) answer
//! false.
use regex::Regex;
use std::sync::LazyLock;

/// The start of a file, and whether it is all of it.
pub(crate) struct Prefix<'a> {
    pub(crate) text: &'a str,
    pub(crate) complete: bool,
}

impl Prefix<'_> {
    /// Ruby's `data.split("\n", -1)`: an empty file has no lines, and a
    /// trailing newline leaves an empty last line.
    fn lines(&self) -> Vec<&str> {
        if self.text.is_empty() {
            Vec::new()
        } else {
            self.text.split('\n').collect()
        }
    }
}

/// Ruby's `File.extname`: the last dot-suffix of the base name, ignoring
/// leading dots, so `.profile` has none.
fn extname(path: &str) -> &str {
    let name = path.rsplit('/').next().unwrap_or(path);
    let trimmed = name.trim_start_matches('.');
    match trimmed.rfind('.') {
        Some(index) => &trimmed[index..],
        None => "",
    }
}

fn regex(pattern: &str) -> Regex {
    Regex::new(pattern).expect("Linguist pattern compiles")
}

macro_rules! patterns {
    ($($name:ident = $pattern:expr;)*) => {
        $(static $name: LazyLock<Regex> = LazyLock::new(|| regex($pattern));)*
    };
}

patterns! {
    INTELLIJ = r"(?:^|/)\.idea/";
    COCOAPODS = r"(^Pods|/Pods)/";
    CARTHAGE_BUILD = r"(^|/)Carthage/Build/";
    NET_DESIGNER = r"(?i)\.designer\.(cs|vb)$";
    SPECFLOW_FEATURE = r"(?i)\.feature\.cs$";
    // Linguist's `(?!-)[-0-9A-Za-z]+(?<!-)`: a label that neither starts
    // nor ends with a hyphen, written without lookaround.
    GO_VENDOR = r"vendor/([0-9A-Za-z](?:[-0-9A-Za-z]*[0-9A-Za-z])?\.)+(com|edu|gov|in|me|net|org|fm|io)";
    GO_LOCK = r"(Gopkg|glide)\.lock";
    ESY_LOCK = r"(^|/)(\w+\.)?esy.lock$";
    BUN_LOCK = r"(?:^|/)bun\.lockb?$";
    YARN_PNP = r"(^|/)\.pnp\..*$";
    ZEPHIR = r".\.zep\.(?:c|h|php)$";
    FLAKE_LOCK = r"(^|/)flake\.lock$";
    BAZEL_LOCK = r"(^|/)MODULE\.bazel\.lock$";
    GRADLE_WRAPPER = r"(?i)(?:^|/)gradlew(?:\.bat)?$";
    MAVEN_WRAPPER = r"(?i)(?:^|/)mvnw(?:\.cmd)?$";
    MISE_LOCK = r"(?:^|/)mise(?:\.[^/]+)?\.lock$";
    SECRETS_BASELINE = r"(?:^|/)\.secrets\.baseline$";
    JULIA_MANIFEST = r"(?:^|/)(Julia)?Manifest(-v\d+\.\d+)?\.toml$";
    TERRAFORM_LOCK = r"(?:^|/)\.terraform\.lock\.hcl$";
    PASCAL_TLB = r"(?i)_tlb\.pas$";
    HTMLCOV = r"(?:^|/)htmlcov/";
    SQLX_QUERY = r"(?:^|/)\.sqlx/query-[a-f\d]{64}\.json$";
    SOURCE_MAP_NAME = r"(?i)(\.css|\.js)\.map$";

    SOURCE_MAP_REFERENCE = r"^/[*/][#@] source(?:Mapping)?URL|sourceURL=";
    SOURCE_MAP_V2 = r#"^\{"version":\d+,"#;
    SOURCE_MAP_V1 = r"^/\*\* Begin line maps\. \*\*/\{";
    COFFEE_HEADER = r"^// Generated by ";
    COFFEE_TEMPS = r"(_fn|_i|_len|_ref|_results)";
    COFFEE_HELPERS = r"(__bind|__extends|__hasProp|__indexOf|__slice)";
    PEG_JS = r"^(?:[^/]|/[^*])*/\*(?:[^*]|\*[^/])*Generated by PEG.js";
    POSTSCRIPT_FONT = r"(?m)^\s*(?:currentfile eexec\s+|/sfnts\s+\[\s<)";
    POSTSCRIPT_CREATOR = r"^%%Creator: ";
    POSTSCRIPT_GENERATOR = r"[0-9]|draw|mpage|ImageMagick|inkscape|MATLAB";
    POSTSCRIPT_GENERATOR_2 = r"PCBNEW|pnmtops|\(Unknown\)|Serif Affinity|Filterimage -tops";
    POSTSCRIPT_EAGLE_TITLE = r"^%%Title: EAGLE Drawing ";
    GO_HEADER = r"^// Code generated .*";
    DART_HEADER = r"generated code\W{2,3}do not modify";
    PPPORT_NAME = r"ppport\.h$";
    GAMEMAKER_JSON = r"^\s*[\{\[]";
    GAMEMAKER_LEGACY = r"^\d\.\d\.\d.+\|\{";
    GIMP_SOURCE = r"^/\* GIMP [a-zA-Z0-9\- ]+ C-Source image dump \(.+?\.c\) \*/";
    GIMP_HEADER = r"^/\*  GIMP header image file format \([a-zA-Z0-9\- ]+\): .+?\.h  \*/";
    PKGDOWN = r"<!-- Generated by pkgdown: do not edit by hand -->";
    DOXYGEN = r"(?i)<!--\s+Generated by Doxygen\s+[.0-9]+\s*-->";
    HTML_META = r"(?i)<meta(\s+[^>]+)>";
    // Linguist's lookbehind `(?<=^|\s)` becomes a consumed boundary; values
    // never contain the whitespace it consumes.
    HTML_META_ATTRIBUTE = r#"(?i)(?:^|\s)(name|content|value)\s*=\s*("[^"]+"|'[^']+'|[^\s"']+)"#;
    HTML_GENERATOR = r"(?i)^(org\s+mode|j?latex2html|groff|makeinfo|texi2html|ronn)\b";
    SORBET_TYPED = r"^# typed:";
    SORBET_TAPIOCA = r"^# Please (run|instead update this file by running) `bin/tapioca";
}

/// Linguist's name rules: the path alone decides.
pub(crate) fn by_path(path: &str) -> bool {
    let ext = extname(path);
    [".nib", ".xcworkspacedata", ".xcuserstate"].contains(&ext)
        || INTELLIJ.is_match(path)
        || COCOAPODS.is_match(path)
        || CARTHAGE_BUILD.is_match(path)
        || path.contains("__generated__/")
        || NET_DESIGNER.is_match(path)
        || SPECFLOW_FEATURE.is_match(path)
        || path.contains("composer.lock")
        || path.contains("Cargo.lock")
        || path.contains("Cargo.toml.orig")
        || path.contains("deno.lock")
        || FLAKE_LOCK.is_match(path)
        || BAZEL_LOCK.is_match(path)
        || path.contains("node_modules/")
        || GO_VENDOR.is_match(path)
        || GO_LOCK.is_match(path)
        || path.contains("Package.resolved")
        || path.contains("poetry.lock")
        || path.contains("pdm.lock")
        || path.contains("uv.lock")
        || path.contains("pixi.lock")
        || ESY_LOCK.is_match(path)
        || path.contains("npm-shrinkwrap.json")
        || path.contains("package-lock.json")
        || path.contains("pnpm-lock.yaml")
        || BUN_LOCK.is_match(path)
        || TERRAFORM_LOCK.is_match(path)
        || YARN_PNP.is_match(path)
        || path.contains("Godeps/")
        || ZEPHIR.is_match(path)
        || HTMLCOV.is_match(path)
        || (ext.eq_ignore_ascii_case(".map") && SOURCE_MAP_NAME.is_match(path))
        || path.contains("Pipfile.lock")
        || GRADLE_WRAPPER.is_match(path)
        || MAVEN_WRAPPER.is_match(path)
        || MISE_LOCK.is_match(path)
        || SECRETS_BASELINE.is_match(path)
        || JULIA_MANIFEST.is_match(path)
        || PASCAL_TLB.is_match(path)
        || SQLX_QUERY.is_match(path)
}

/// One content rule: the guard Linguist checks before reading data, and the
/// check itself.
struct ContentRule {
    guard: fn(&str, &str) -> bool,
    check: fn(&Prefix<'_>, &[&str]) -> bool,
}

const PROTOBUF_EXTENSIONS: &[&str] = &[".py", ".java", ".h", ".cc", ".cpp", ".m", ".rb", ".php"];
const APACHE_THRIFT_EXTENSIONS: &[&str] = &[
    ".rb", ".py", ".go", ".js", ".m", ".java", ".h", ".cc", ".cpp", ".php",
];
const HAXE_EXTENSIONS: &[&str] = &[".js", ".py", ".lua", ".cpp", ".h", ".java", ".cs", ".php"];

fn maybe_minified(ext: &str) -> bool {
    ext.eq_ignore_ascii_case(".js") || ext.eq_ignore_ascii_case(".css")
}

fn first<'a>(lines: &'a [&'a str], count: usize) -> &'a [&'a str] {
    &lines[..lines.len().min(count)]
}

fn line_contains(lines: &[&str], index: usize, needle: &str) -> bool {
    lines.get(index).is_some_and(|line| line.contains(needle))
}

fn second_to_last<'a>(lines: &[&'a str]) -> Option<&'a str> {
    lines.len().checked_sub(2).map(|index| lines[index])
}

const CONTENT_RULES: &[ContentRule] = &[
    // minified_files?
    ContentRule {
        guard: |_, ext| maybe_minified(ext),
        check: |_, lines| {
            !lines.is_empty()
                && lines.iter().map(|line| line.chars().count()).sum::<usize>() / lines.len() > 110
        },
    },
    // has_source_map?
    ContentRule {
        guard: |_, ext| maybe_minified(ext),
        check: |prefix, lines| {
            prefix.complete
                && lines[lines.len().saturating_sub(2)..]
                    .iter()
                    .any(|line| SOURCE_MAP_REFERENCE.is_match(line))
        },
    },
    // source_map?, by content
    ContentRule {
        guard: |_, ext| ext.eq_ignore_ascii_case(".map"),
        check: |_, lines| {
            lines
                .first()
                .is_some_and(|line| SOURCE_MAP_V2.is_match(line) || SOURCE_MAP_V1.is_match(line))
        },
    },
    // compiled_coffeescript?
    ContentRule {
        guard: |_, ext| ext == ".js",
        check: |prefix, lines| {
            if lines
                .first()
                .is_some_and(|line| COFFEE_HEADER.is_match(line))
            {
                return true;
            }
            if !(prefix.complete
                && lines.first() == Some(&"(function() {")
                && second_to_last(lines) == Some("}).call(this);")
                && lines.last() == Some(&""))
            {
                return false;
            }
            let score: usize = lines
                .iter()
                .filter(|line| line.contains("var "))
                .map(|line| {
                    COFFEE_TEMPS.find_iter(line).count()
                        + 3 * COFFEE_HELPERS.find_iter(line).count()
                })
                .sum();
            score >= 3
        },
    },
    // generated_parser?
    ContentRule {
        guard: |_, ext| ext == ".js",
        check: |_, lines| PEG_JS.is_match(&first(lines, 5).concat()),
    },
    // generated_net_docfile?
    ContentRule {
        guard: |_, ext| ext.eq_ignore_ascii_case(".xml"),
        check: |prefix, lines| {
            prefix.complete
                && lines.len() > 3
                && lines[1].contains("<doc>")
                && lines[2].contains("<assembly>")
                && second_to_last(lines).is_some_and(|line| line.contains("</doc>"))
        },
    },
    // generated_postscript?
    ContentRule {
        guard: |_, ext| [".ps", ".eps", ".pfa"].contains(&ext),
        check: |prefix, lines| {
            if POSTSCRIPT_FONT.is_match(prefix.text) {
                return true;
            }
            let Some(creator) = first(lines, 10)
                .iter()
                .find(|line| POSTSCRIPT_CREATOR.is_match(line))
            else {
                return false;
            };
            if POSTSCRIPT_GENERATOR.is_match(creator) || POSTSCRIPT_GENERATOR_2.is_match(creator) {
                return true;
            }
            creator.contains("EAGLE")
                && first(lines, 5)
                    .iter()
                    .any(|line| POSTSCRIPT_EAGLE_TITLE.is_match(line))
        },
    },
    // generated_go?
    ContentRule {
        guard: |_, ext| ext == ".go",
        check: |_, lines| {
            lines.len() > 1 && first(lines, 40).iter().any(|line| GO_HEADER.is_match(line))
        },
    },
    // generated_protocol_buffer_from_go?
    ContentRule {
        guard: |_, ext| ext == ".proto",
        check: |_, lines| {
            lines.len() > 1
                && first(lines, 20)
                    .iter()
                    .any(|line| line.contains("This file was autogenerated by go-to-protobuf"))
        },
    },
    // generated_protocol_buffer?
    ContentRule {
        guard: |_, ext| PROTOBUF_EXTENSIONS.contains(&ext),
        check: |_, lines| {
            lines.len() > 1
                && first(lines, 3).iter().any(|line| {
                    line.contains("Generated by the protocol buffer compiler.  DO NOT EDIT!")
                })
        },
    },
    // generated_javascript_protocol_buffer?
    ContentRule {
        guard: |_, ext| ext == ".js",
        check: |_, lines| lines.len() > 6 && lines[5].contains("GENERATED CODE -- DO NOT EDIT!"),
    },
    // generated_typescript_protocol_buffer?
    ContentRule {
        guard: |_, ext| ext == ".ts",
        check: |_, lines| {
            lines.len() > 4
                && lines[0].contains("Code generated by protoc-gen-ts_proto. DO NOT EDIT.")
        },
    },
    // generated_twirp_ruby?
    ContentRule {
        guard: |_, ext| ext == ".rb",
        check: |_, lines| {
            lines.len() > 1
                && first(lines, 3).iter().any(|line| {
                    line.contains("Code generated by protoc-gen-twirp_ruby")
                        && line.contains("DO NOT EDIT.")
                })
        },
    },
    // generated_apache_thrift?
    ContentRule {
        guard: |_, ext| APACHE_THRIFT_EXTENSIONS.contains(&ext),
        check: |_, lines| {
            first(lines, 6)
                .iter()
                .any(|line| line.contains("Autogenerated by Thrift Compiler"))
        },
    },
    // generated_jni_header?
    ContentRule {
        guard: |_, ext| ext == ".h",
        check: |_, lines| {
            lines.len() > 2
                && lines[0].contains("/* DO NOT EDIT THIS FILE - it is machine generated */")
                && lines[1].contains("#include <jni.h>")
        },
    },
    // vcr_cassette?
    ContentRule {
        guard: |_, ext| ext == ".yml",
        check: |prefix, lines| {
            prefix.complete
                && lines.len() > 2
                && second_to_last(lines).is_some_and(|line| line.contains("recorded_with: VCR"))
        },
    },
    // generated_antlr?
    ContentRule {
        guard: |_, ext| ext == ".g",
        check: |_, lines| lines.len() > 2 && lines[1].contains("generated by Xtest"),
    },
    // compiled_cython_file?
    ContentRule {
        guard: |_, ext| [".c", ".cpp"].contains(&ext),
        check: |_, lines| lines.len() > 1 && lines[0].contains("Generated by Cython"),
    },
    // generated_module?
    ContentRule {
        guard: |_, ext| ext == ".mod",
        check: |_, lines| {
            lines.len() > 1
                && (lines[0].contains("PCBNEW-LibModule-V")
                    || lines[0].contains("GFORTRAN module version '"))
        },
    },
    // generated_unity3d_meta?
    ContentRule {
        guard: |_, ext| ext == ".meta",
        check: |_, lines| lines.len() > 1 && lines[0].contains("fileFormatVersion: "),
    },
    // generated_racc?
    ContentRule {
        guard: |_, ext| ext == ".rb",
        check: |_, lines| {
            lines.len() > 2
                && lines[2].starts_with("# This file is automatically generated by Racc")
        },
    },
    // generated_jflex?
    ContentRule {
        guard: |_, ext| ext == ".java",
        check: |_, lines| {
            lines.len() > 1 && lines[0].starts_with("/* The following code was generated by JFlex ")
        },
    },
    // generated_grammarkit?
    ContentRule {
        guard: |_, ext| ext == ".java",
        check: |_, lines| {
            lines.len() > 1
                && lines[0]
                    .starts_with("// This is a generated file. Not intended for manual editing.")
        },
    },
    // generated_roxygen2?
    ContentRule {
        guard: |_, ext| ext == ".Rd",
        check: |_, lines| {
            lines.len() > 1 && lines[0].contains("% Generated by roxygen2: do not edit by hand")
        },
    },
    // generated_html?
    ContentRule {
        guard: |_, ext| {
            [".html", ".htm", ".xhtml"]
                .iter()
                .any(|html| ext.eq_ignore_ascii_case(html))
        },
        check: |_, lines| generated_html(lines),
    },
    // generated_jison?
    ContentRule {
        guard: |_, ext| ext == ".js",
        check: |_, lines| {
            lines.len() > 1
                && (lines[0].starts_with("/* parser generated by jison ")
                    || lines[0].starts_with("/* generated by jison-lex "))
        },
    },
    // generated_grpc_cpp?
    ContentRule {
        guard: |_, ext| [".cpp", ".hpp", ".h", ".cc"].contains(&ext),
        check: |_, lines| lines.len() > 1 && lines[0].starts_with("// Generated by the gRPC"),
    },
    // generated_dart?
    ContentRule {
        guard: |_, ext| ext == ".dart",
        check: |_, lines| {
            lines.len() > 1
                && first(lines, 3)
                    .iter()
                    .any(|line| DART_HEADER.is_match(&line.to_lowercase()))
        },
    },
    // generated_perl_ppport_header?
    ContentRule {
        guard: |path, _| PPPORT_NAME.is_match(path),
        check: |_, lines| {
            lines.len() > 10 && lines[8].contains("Automatically created by Devel::PPPort")
        },
    },
    // generated_gamemakerstudio?
    ContentRule {
        guard: |_, ext| [".yy", ".yyp"].contains(&ext),
        check: |_, lines| {
            lines.len() > 3
                && (GAMEMAKER_JSON.is_match(&first(lines, 3).concat())
                    || GAMEMAKER_LEGACY.is_match(lines[0]))
        },
    },
    // generated_gimp?
    ContentRule {
        guard: |_, ext| [".c", ".h"].contains(&ext),
        check: |_, lines| {
            lines
                .first()
                .is_some_and(|line| GIMP_SOURCE.is_match(line) || GIMP_HEADER.is_match(line))
        },
    },
    // generated_visualstudio6?
    ContentRule {
        guard: |_, ext| ext.eq_ignore_ascii_case(".dsp"),
        check: |_, lines| {
            first(lines, 3)
                .iter()
                .any(|line| line.contains("# Microsoft Developer Studio Generated Build File"))
        },
    },
    // generated_haxe?
    ContentRule {
        guard: |_, ext| HAXE_EXTENSIONS.contains(&ext),
        check: |_, lines| {
            first(lines, 3)
                .iter()
                .any(|line| line.contains("Generated by Haxe"))
        },
    },
    // generated_jooq?
    ContentRule {
        guard: |_, ext| ext.eq_ignore_ascii_case(".java"),
        check: |_, lines| {
            first(lines, 2)
                .iter()
                .any(|line| line.contains("This file is generated by jOOQ."))
        },
    },
    // generated_sorbet_rbi?
    ContentRule {
        guard: |_, ext| ext.eq_ignore_ascii_case(".rbi"),
        check: |_, lines| {
            lines.len() >= 5
                && SORBET_TYPED.is_match(lines[0])
                && lines[2].contains("DO NOT EDIT MANUALLY")
                && SORBET_TAPIOCA.is_match(lines[4])
        },
    },
    // generated_mysql_view_definition_format?
    ContentRule {
        guard: |_, ext| ext.eq_ignore_ascii_case(".frm"),
        check: |_, lines| line_contains(lines, 0, "TYPE=VIEW"),
    },
];

/// Pkgdown, mandoc and Doxygen markers, or a `<meta name="generator">` naming
/// a documentation tool, near the top of an HTML file.
fn generated_html(lines: &[&str]) -> bool {
    if lines.len() <= 1 {
        return false;
    }
    if first(lines, 2).iter().any(|line| PKGDOWN.is_match(line)) {
        return true;
    }
    if lines.len() > 2 && lines[2].starts_with("<!-- This is an automatically generated file.") {
        return true;
    }
    let head = first(lines, 31);
    if head.iter().any(|line| DOXYGEN.is_match(line)) {
        return true;
    }
    let joined = head.join(" ");
    HTML_META.captures_iter(&joined).any(|meta| {
        let attributes = meta[1].strip_suffix('/').unwrap_or(&meta[1]).trim();
        let mut name = None;
        let mut values = Vec::new();
        for attribute in HTML_META_ATTRIBUTE.captures_iter(attributes) {
            let value = attribute[2].trim_matches(|c| c == '"' || c == '\'');
            match attribute[1].to_lowercase().as_str() {
                "name" => name = Some(value.to_lowercase()),
                _ => values.push(value.to_owned()),
            }
        }
        name.as_deref() == Some("generator")
            && values.iter().any(|value| HTML_GENERATOR.is_match(value))
    })
}

/// Whether any content rule could apply to this path, so its content is
/// worth reading.
pub(crate) fn needs_content(path: &str) -> bool {
    let ext = extname(path);
    CONTENT_RULES.iter().any(|rule| (rule.guard)(path, ext))
}

/// Linguist's content rules over the start of the file.
pub(crate) fn by_content(path: &str, prefix: &Prefix<'_>) -> bool {
    let ext = extname(path);
    let lines = prefix.lines();
    CONTENT_RULES
        .iter()
        .any(|rule| (rule.guard)(path, ext) && (rule.check)(prefix, &lines))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn whole(text: &str) -> Prefix<'_> {
        Prefix {
            text,
            complete: true,
        }
    }

    #[test]
    fn extname_matches_ruby() {
        assert_eq!(extname("a/b.min.JS"), ".JS");
        assert_eq!(extname("a/.profile"), "");
        assert_eq!(extname("Makefile"), "");
        assert_eq!(extname("dir.d/file"), "");
    }

    #[test]
    fn names_and_paths() {
        for path in [
            "Cargo.lock",
            "sub/Cargo.lock",
            "web/package-lock.json",
            "pnpm-lock.yaml",
            "bun.lockb",
            "uv.lock",
            "go/Gopkg.lock",
            "node_modules/left-pad/index.js",
            "vendor/github.com/pkg/errors/errors.go",
            "src/__generated__/Query.graphql.ts",
            "App.xcworkspacedata",
            ".idea/workspace.xml",
            "Pods/Alamofire/Source.swift",
            "Carthage/Build/iOS/x.framework",
            "Form1.Designer.cs",
            "infra/.terraform.lock.hcl",
            "flake.lock",
            "MODULE.bazel.lock",
            "gradlew",
            "mvnw.cmd",
            "mise.local.lock",
            ".secrets.baseline",
            "JuliaManifest.toml",
            "htmlcov/index.html",
            "assets/app.js.map",
            "Unit1_TLB.pas",
            ".pnp.cjs",
            "ext/kernel/main.zep.c",
            ".sqlx/query-0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef.json",
        ] {
            assert!(by_path(path), "{path}");
        }
        for path in [
            "src/main.rs",
            "Cargo.toml",
            "vendor/-bad-.com/x.go",
            "docs/lock.md",
            "assets/app.map",
        ] {
            assert!(!by_path(path), "{path}");
        }
    }

    #[test]
    fn headers_in_the_first_lines() {
        let cases = [
            ("api/service.pb.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n"),
            ("gen/a_pb2.py", "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n# source: a.proto\n"),
            ("a.ts", "// Code generated by protoc-gen-ts_proto. DO NOT EDIT.\n// versions:\n//   x\n// source: a.proto\n\n"),
            ("lib.js", "// Generated by CoffeeScript 1.12.7\n(function() {\n"),
            ("gen/Thing.java", "/**\n * Autogenerated by Thrift Compiler (0.9.3)\n */\n"),
            ("native.h", "/* DO NOT EDIT THIS FILE - it is machine generated */\n#include <jni.h>\n\n"),
            ("model.g.dart", "// GENERATED CODE - DO NOT MODIFY BY HAND\n\npart of 'model.dart';\n"),
            ("x.c", "/* Generated by Cython 3.0.0 */\n\n"),
            ("man.Rd", "% Generated by roxygen2: do not edit by hand\n% Please edit documentation in R/x.R\n"),
            ("page.html", "<html>\n<head>\n<meta name=\"generator\" content=\"groff -Thtml\">\n</head>\n"),
            ("ref.html", "<html>\n<!-- Generated by Doxygen 1.9.1 -->\n"),
            ("img.c", "/* GIMP RGB C-Source image dump (img.c) */\n\n"),
            ("rbi/foo.rbi", "# typed: true\n\n# DO NOT EDIT MANUALLY\n# This is an autogenerated file\n# Please run `bin/tapioca dsl Foo`.\n"),
            ("view.frm", "TYPE=VIEW\nquery=select 1\n"),
            ("fig.eps", "%!PS-Adobe-3.0 EPSF-3.0\n%%Creator: cairo 1.16.0\n"),
        ];
        for (path, text) in cases {
            assert!(needs_content(path), "{path}");
            assert!(by_content(path, &whole(text)), "{path}");
        }
        assert!(!by_content(
            "api/service.go",
            &whole("package api\n\nfunc main() {}\n")
        ));
        assert!(!by_content(
            "page.html",
            &whole("<html>\n<head>\n<meta name=\"generator\" content=\"Hugo 0.1\">\n")
        ));
        assert!(!needs_content("src/main.rs"));
        assert!(!needs_content("README.md"));
    }

    #[test]
    fn minified_by_average_line_length() {
        let long = format!("var a={};\n", "x".repeat(300));
        assert!(by_content("app.js", &whole(&long)));
        assert!(by_content("site.CSS", &whole(&long)));
        let short = "function a() {\n  return 1;\n}\n";
        assert!(!by_content("app.js", &whole(short)));
        // Only JavaScript and CSS are measured.
        assert!(!by_content("data.json", &whole(&long)));
    }

    #[test]
    fn tail_rules_need_the_whole_file() {
        let mapped = "var a = 1;\n//# sourceMappingURL=app.js.map\n";
        assert!(by_content("app.js", &whole(mapped)));
        let truncated = Prefix {
            text: mapped,
            complete: false,
        };
        assert!(!by_content("app.js", &truncated));
        let cassette = "---\nhttp_interactions: []\nrecorded_with: VCR 6.0.0\n";
        assert!(by_content("fixtures/c.yml", &whole(cassette)));
    }
}
