[package]
workspace = "../../../workspace"
publish = false
name = "diffr-plugin-test-bodies"
description = "The test-bodies plugin: collapse test bodies and test modules."
version = "0.1.1"
edition = "2021"
rust-version = "1.85.0"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
diffr-plugin-sdk = { path = "../../../../crates/diffr-plugin-sdk", version = "0.3.0" }
serde = { version = "1.0", features = ["derive"] }

serde_json = "1.0"
