import * as stylex from "@stylexjs/stylex";

import {
  traceGroupMarker,
  traceRowMarker,
  traceToolMarker,
  traceWorkedMarker,
} from "./markers.stylex";
import { elevation, fontWeight } from "./scale.stylex";
import { tokens } from "./tokens.stylex";

// The agent trace view, and the trace scoped into a side peek.
export const traceStyles = stylex.create({
  region: {
    overflow: "auto",
    // The trace view anchors scroll itself across elision changes; the
    // browser's own heuristic would otherwise adjust a second time.
    overflowAnchor: "none",
  },
  view: {
    minHeight: "100%",
    // The left inset clears the event ruler: 14px edge inset + 6px resting
    // tick + 28px gap, so the 30px hover comb stops just short of the text.
    padding: "36px 24px 96px 48px",
  },
  column: {
    width: "min(980px, 100%)",
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
  },
  kicker: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: tokens.inkFaint,
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    paddingBottom: "24px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.rule,
  },
  title: {
    margin: 0,
    fontFamily: tokens.fontSerif,
    fontSize: "22px",
    lineHeight: "28px",
    fontWeight: 500,
    color: tokens.ink,
  },
  meta: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "8px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.inkFaint,
  },
  metaSeparator: {
    color: tokens.ruleSoft,
  },

  picker: {
    position: "relative",
    display: "inline-block",
    marginBottom: "20px",
  },
  // A secondary Button that stands off the page like a select.
  pickerTrigger: {
    justifyContent: "flex-start",
    gap: "8px",
    maxWidth: "min(680px, 100%)",
    borderColor: { default: tokens.rule, ":hover": tokens.ruleSoft },
    backgroundColor: { default: tokens.surface, ":hover": tokens.tray },
    color: tokens.ink,
    fontWeight: fontWeight.regular,
    boxShadow: elevation.raised,
  },
  pickerTriggerOpen: {
    borderColor: tokens.accent,
    boxShadow: `0 0 0 2px ${tokens.accentWash}`,
  },
  pickerHarness: {
    fontFamily: tokens.fontMono,
    fontSize: "10.5px",
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: tokens.accent,
    flexShrink: 0,
  },
  pickerTitle: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: 500,
    color: tokens.ink,
  },
  pickerChevron: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "12px",
    height: "12px",
    marginLeft: "2px",
    flexShrink: 0,
    color: tokens.inkFaint,
    transition: "transform 0.15s ease",
  },
  pickerChevronOpen: {
    transform: "rotate(180deg)",
  },
  pickerMenu: {
    position: "absolute",
    top: "calc(100% + 4px)",
    left: 0,
    zIndex: 50,
    minWidth: "320px",
    maxWidth: "min(640px, 90vw)",
    backgroundColor: tokens.surface,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens.rule,
    borderRadius: "6px",
    boxShadow: `0 6px 20px ${tokens.shadowColorStrong}`,
    padding: "4px",
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  pickerItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    width: "100%",
    padding: "6px 10px",
    borderRadius: "4px",
    borderWidth: 0,
    borderStyle: "none",
    borderColor: "currentcolor",
    backgroundColor: { default: "transparent", ":hover": tokens.tray },
    color: tokens.ink,
    fontSize: "12.5px",
    textAlign: "left",
    cursor: "pointer",
    transition: "background 0.1s ease",
  },
  pickerItemActive: {
    backgroundColor: tokens.accentWash,
    color: tokens.accent,
  },
  pickerItemSubagent: {
    paddingLeft: "20px",
  },
  pickerItemLeft: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    overflow: "hidden",
    minWidth: 0,
    flex: "1",
  },
  pickerItemHarness: {
    fontFamily: tokens.fontMono,
    fontSize: "10.5px",
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: tokens.inkMuted,
    flexShrink: 0,
    minWidth: "52px",
  },
  pickerItemHarnessActive: {
    color: tokens.accent,
  },
  pickerItemTitle: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: 400,
  },
  pickerItemTitleActive: {
    fontWeight: 600,
  },
  pickerItemCheck: {
    fontSize: "12px",
    fontWeight: 700,
    color: tokens.accent,
    flexShrink: 0,
    marginLeft: "6px",
  },
  pickerItemBadge: {
    fontFamily: tokens.fontMono,
    fontSize: "9.5px",
    padding: "1px 4px",
    borderRadius: "3px",
    backgroundColor: tokens.tray,
    color: tokens.inkFaint,
    textTransform: "uppercase",
    flexShrink: 0,
  },

  events: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
    marginTop: "28px",
  },
  // In a side peek.
  eventsScoped: {
    marginTop: "22px",
  },
  turn: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
  },
  // An elided message sets its own prose; a whole one leaves it to markdown.
  proseElided: {
    fontFamily: tokens.fontSerif,
    fontSize: "15px",
    lineHeight: "26px",
    color: tokens.ink,
  },
  proseMarkdown: {
    fontFamily: tokens.fontSerif,
    fontSize: "15px",
    lineHeight: "26px",
    color: tokens.ink,
    overflowWrap: "anywhere",
  },

  tool: {
    minWidth: 0,
  },
  summary: {
    listStyle: "none",
    cursor: "pointer",
    "::-webkit-details-marker": {
      display: "none",
    },
  },
  toolRow: {
    display: "grid",
    gridTemplateColumns: "20px minmax(0, 1fr) 16px",
    columnGap: "6px",
    alignItems: "center",
    minHeight: "24px",
  },
  icon: {
    width: "14px",
    height: "14px",
    fill: "none",
    stroke: tokens.inkFaint,
    strokeWidth: 1.5,
    strokeLinecap: "round",
    strokeLinejoin: "round",
  },
  centered: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  toolLabel: {
    display: "flex",
    alignItems: "baseline",
    gap: "6px",
    minWidth: 0,
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    lineHeight: "19px",
  },
  toolVerb: {
    color: tokens.inkFaint,
    flexShrink: 0,
  },
  toolTitle: {
    color: tokens.inkMuted,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  toolTitleFile: {
    color: tokens.accent,
    // Ellipsize the FRONT of paths so the filename stays visible.
    direction: "rtl",
    textAlign: "left",
  },
  toolPath: {
    unicodeBidi: "plaintext",
  },
  added: {
    color: tokens.changeAdded,
    flexShrink: 0,
  },
  removed: {
    color: tokens.changeRemoved,
    flexShrink: 0,
  },
  errorFlag: {
    color: tokens.changeRemoved,
    fontSize: "10px",
    fontWeight: 600,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    flexShrink: 0,
  },
  toolChevronIcon: {
    width: "12px",
    height: "12px",
    stroke: tokens.ruleSoft,
    transform: {
      default: "rotate(-90deg)",
      [stylex.when.ancestor(":is([open])", traceToolMarker)]: "rotate(0deg)",
    },
    transition: "transform 120ms ease",
  },

  // The embedded workbench Chromium does not hide closed details content.
  figure: {
    display: {
      default: null,
      [stylex.when.ancestor(":not([open])", traceToolMarker)]: "none",
    },
    margin: "10px 0 0 26px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens.rule,
    borderRadius: "8px",
    backgroundColor: tokens.surface,
    overflow: "hidden",
  },
  figureHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "30px",
    padding: "0 12px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.rule,
    backgroundColor: tokens.tray,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: tokens.inkFaint,
  },
  figureBody: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    margin: 0,
    padding: "14px 16px",
    maxHeight: "420px",
    overflow: "auto",
    fontFamily: tokens.fontMono,
    fontSize: "12.5px",
    lineHeight: "20px",
    whiteSpace: "pre-wrap",
    overflowWrap: "break-word",
  },
  figureBodyThinking: {
    whiteSpace: "normal",
    fontFamily: tokens.fontSerif,
    fontSize: "14px",
    lineHeight: "22px",
    color: tokens.inkMuted,
  },
  thinkingMarkdown: {
    fontFamily: "inherit",
    fontSize: "inherit",
    lineHeight: "inherit",
    color: "inherit",
  },
  figureCommand: {
    color: tokens.ink,
  },
  figureOutput: {
    color: tokens.inkMuted,
  },

  workedSummary: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    margin: "6px 0 0",
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: { default: tokens.inkFaint, ":hover": tokens.inkMuted },
  },
  inlineCentered: {
    display: "inline-flex",
    alignItems: "center",
  },
  workedChevronIcon: {
    width: "11px",
    height: "11px",
    stroke: tokens.inkFaint,
    transform: {
      default: "rotate(-90deg)",
      [stylex.when.ancestor(":is([open])", traceWorkedMarker)]: "rotate(0deg)",
    },
    transition: "transform 120ms ease",
  },
  line: {
    flexGrow: 1,
    height: "1px",
    backgroundColor: tokens.rule,
  },
  workedBody: {
    display: {
      default: "flex",
      [stylex.when.ancestor(":not([open])", traceWorkedMarker)]: "none",
    },
    flexDirection: "column",
    gap: "18px",
    marginTop: "18px",
  },

  // Coalesced tool runs: one summary row per consecutive tool-call run.
  toolGroupSummary: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minHeight: "24px",
    fontFamily: tokens.fontMono,
    fontSize: "12.5px",
    color: tokens.inkMuted,
  },
  toolGroupLabel: {
    color: tokens.inkMuted,
  },
  toolGroupCount: {
    color: tokens.inkFaint,
    fontSize: "11px",
  },
  toolGroupChevronIcon: {
    width: "12px",
    height: "12px",
    stroke: tokens.ruleSoft,
    transform: {
      default: "rotate(-90deg)",
      [stylex.when.ancestor(":is([open])", traceGroupMarker)]: "rotate(0deg)",
    },
    transition: "transform 120ms ease",
  },
  toolGroupBody: {
    display: {
      default: "flex",
      [stylex.when.ancestor(":not([open])", traceGroupMarker)]: "none",
    },
    flexDirection: "column",
    gap: "18px",
    padding: "2px 0 4px 26px",
  },

  note: {
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    lineHeight: "19px",
    color: tokens.inkFaint,
  },
  noteError: {
    color: tokens.changeRemoved,
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    paddingTop: "48px",
    fontFamily: tokens.fontSerif,
    fontSize: "15px",
    lineHeight: "26px",
    color: tokens.ink,
  },
  flush: {
    margin: 0,
  },

  // Lens rows. A gap row marks hidden events with dashes; a collapse row,
  // solid, marks the boundary of a revealed span.
  lensRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    margin: "4px 0",
    padding: 0,
    borderWidth: 0,
    borderStyle: "none",
    borderColor: "currentcolor",
    backgroundColor: "transparent",
    cursor: "pointer",
    width: "100%",
  },
  lensLine: {
    flexGrow: 1,
    height: "1px",
    borderTopWidth: "1px",
    borderTopStyle: "dashed",
    borderTopColor: tokens.ruleSoft,
  },
  lensLineSolid: {
    borderTopStyle: "solid",
    borderColor: {
      default: null,
      [stylex.when.ancestor(":hover", traceRowMarker)]: tokens.inkFaint,
    },
    borderTopColor: {
      default: tokens.ruleSoft,
      [stylex.when.ancestor(":hover", traceRowMarker)]: tokens.inkFaint,
    },
  },
  lensRowChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    height: "22px",
    padding: "0 10px",
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: {
      default: tokens.ruleSoft,
      [stylex.when.ancestor(":hover", traceRowMarker)]: tokens.inkFaint,
    },
    borderRadius: "999px",
    backgroundColor: tokens.surface,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    fontWeight: 600,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: {
      default: tokens.inkFaint,
      [stylex.when.ancestor(":hover", traceRowMarker)]: tokens.inkMuted,
    },
    whiteSpace: "nowrap",
  },
  lensRowChipSolid: {
    borderStyle: "solid",
  },
  collapseChevron: {
    width: "10px",
    height: "10px",
    flexShrink: 0,
    fill: "none",
    stroke: "currentColor",
    strokeWidth: 1.8,
    strokeLinecap: "round",
    strokeLinejoin: "round",
  },
  userSlot: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
    width: "100%",
  },
  elided: {
    display: "inline",
  },
  kept: {
    fontFamily: tokens.fontSerif,
    fontSize: "15px",
    lineHeight: "26px",
    color: tokens.ink,
  },
  keptInBubble: {
    lineHeight: "24px",
  },
  lensChip: {
    display: "inline-flex",
    alignItems: "center",
    height: "18px",
    margin: "0 6px",
    padding: "0 7px",
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: { default: tokens.ruleSoft, ":hover": tokens.inkFaint },
    borderRadius: "999px",
    backgroundColor: tokens.surface,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: { default: tokens.inkFaint, ":hover": tokens.inkMuted },
    cursor: "pointer",
    verticalAlign: "baseline",
  },

  peekOpenFull: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    padding: "3px 8px",
    borderRadius: "4px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens.ruleSoft,
    backgroundColor: { default: tokens.surface, ":hover": tokens.accentWash },
    color: tokens.accent,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    cursor: "pointer",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  source: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    margin: "0 0 0.75rem",
  },
  sourceSelect: {
    font: "inherit",
    color: "inherit",
    backgroundColor: "transparent",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens.rule,
    borderRadius: "4px",
    padding: "0.15rem 0.4rem",
  },
});
