/** Every component's fields, for session_get_instructions: the edit tool's
 * description must stay short enough that clients don't cut it off. */
export const COMPONENT_REFERENCE = [
  "## Components",
  "",
  "session_edit's content is one component, named by its type. Fields, with ? for optional and anchor for a source anchor string:",
  "",
  "- markdown {markdown, pins?}",
  "- code {text, language?, caption?}",
  "- divider {}",
  "- code_peek {source: anchor, caption?, pins?}",
  "- section {title, children: component[], defaultCollapsed?}",
  "- callout {children: component[], title?, tone?: info|warning|danger|success}",
  "- image {assetId from session_upload, alt, caption?}",
  "- trace_quote {traceId, eventId, text}",
  "- software_map {mapVersionId, focusElementId?}",
  "- sequence {title, actors: {key: label}, steps: step[], pins?}",
  "- step {from, to (actor keys), label, style?: call|return|async, and exactly one of source: anchor, sources: anchor[] (1 to 10, in reading order, for a step whose code spans several places), explanation, or code: {text, language?}; pins?}",
  "- flow_diagram {title, nodes: flow_node[] (1 to 100), edges: flow_edge[], description?, direction?: right|down, pins?}",
  "- flow_node {key, label, description?, kind?: process|decision|terminal, attachments?: {label, sources: anchor[], pins?}[], link?: {from or to, label?, style?}}",
  "- flow_edge {from, to (node keys), label?, style?: solid|dashed}",
  "- call_stack_diff {title, base: frame[], head: frame[], pins?}; either side may be empty",
  "- frame {source: anchor, label?, key?, parentKey? (an earlier frame on that side), callSite?: anchor, contextSources?: anchor[], via?: {kind: call|queue|callback|rpc, reason}, pins?}",
  "- database_lens {title, actors: {key: label}, stores: {key: store}, useCases: useCase[] (1 or more), pins?}",
  "- store {label, storage: relational|document, collections: {key: {label, fields: {key: field}}}, dataStoreKind?: database|objectStore|bucket|artifactStore|fileStore}",
  "- field {label, dataType, nullable?, primaryKey?, references?: {store, collection, field}, fields?: {key: field}}",
  "- useCase {label, summary?, operations: operation[] (1 or more)}; operation {kind: read|write, actor, store, collection, label, source: anchor, field?, detail?, pins?}, naming declared keys",
  "",
  'Example (replace its path and lines with verified ones): {"type":"sequence","title":"Request","actors":{"a":"Client","b":"Server"},"steps":[{"from":"a","to":"b","label":"Send","source":"head/src/app.ts#L10-L20"}]}',
].join("\n");
