//! File tags on the stream manifest, from bundled rules and git attributes.
mod support;

mod git_fixture;
use gix::Repository;
use serde_json::Value;
use std::fs;
use std::process::Output;
use support::get_base_command;
use tempfile::TempDir;

/// A repository with a working tree, plus a home directory holding git's
/// user-wide attributes file.
struct Fixture {
    dir: TempDir,
    repo: Repository,
}

impl Fixture {
    fn new() -> Self {
        let dir = tempfile::tempdir().unwrap();
        let repo = gix::init(dir.path().join("repo")).unwrap();
        fs::create_dir_all(dir.path().join("home/.config/git")).unwrap();
        Self { dir, repo }
    }

    fn write(&self, path: &str, text: &str) {
        let path = self.dir.path().join("repo").join(path);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, text).unwrap();
    }

    /// diffr's own config file, under the fixture's home.
    fn config(&self, text: &str) {
        let dir = self.dir.path().join("home/.config/diffr");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("config.toml"), text).unwrap();
    }

    fn user_attributes(&self, text: &str) {
        fs::write(self.dir.path().join("home/.config/git/attributes"), text).unwrap();
    }

    fn commit(&self) -> String {
        git_fixture::commit(&self.repo, "fixture")
    }

    fn run(&self, base: &str, head: &str) -> Output {
        self.diff(&[base, head])
    }

    /// Diff `revisions`: two, or one against the working tree.
    fn diff(&self, revisions: &[&str]) -> Output {
        let home = self.dir.path().join("home");
        get_base_command()
            .arg("--repo")
            .arg(self.dir.path().join("repo"))
            .args(revisions)
            .args(["--format", "ndjson"])
            .env("HOME", &home)
            .env("XDG_CONFIG_HOME", home.join(".config"))
            .env_remove("GIT_DIR")
            .output()
            .unwrap()
    }
}

fn records(output: &Output) -> Vec<Value> {
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout.clone())
        .unwrap()
        .lines()
        .map(|line| serde_json::from_str(line).unwrap())
        .collect()
}

fn path_of(file: &Value) -> &str {
    file.get("rhs").or_else(|| file.get("lhs")).unwrap()["path"]
        .as_str()
        .unwrap()
}

fn tags_of<'a>(records: &'a [Value], path: &str) -> Vec<&'a str> {
    let entry = records[0]["files"]
        .as_array()
        .unwrap()
        .iter()
        .find(|entry| path_of(&entry["file"]) == path)
        .unwrap_or_else(|| panic!("{path} is not in the manifest"));
    match entry.get("tags") {
        Some(tags) => tags
            .as_array()
            .unwrap()
            .iter()
            .map(|tag| tag.as_str().unwrap())
            .collect(),
        None => Vec::new(),
    }
}

fn fallback_of<'a>(records: &'a [Value], path: &str) -> Option<&'a str> {
    let record = records
        .iter()
        .find(|record| record["type"] == "file" && path_of(&record["file"]) == path)
        .unwrap_or_else(|| panic!("{path} has no file record"));
    record["diff"]["stats"]
        .get("fallback")
        .map(|fallback| fallback["code"].as_str().unwrap())
}

#[test]
fn manifest_tags_follow_rules_then_attributes() {
    let fixture = Fixture::new();
    let lock = "[[package]]\nname = \"a\"\nversion = \"1.0.0\"\n";
    let go = "package api\n\nfunc A() int {\n\treturn 1\n}\n";
    fixture.write("Cargo.lock", lock);
    fixture.write("locks/Cargo.lock", lock);
    fixture.write("api/service.go", go);
    fixture.write("src/lib.rs", "fn a() -> u32 {\n    1\n}\n");
    fixture.write("tests/check.py", "def test_a():\n    assert 1\n");
    fixture.write("web/schema.json", "{\"a\": 1}\n");
    fixture.write("user.txt", "one\n");
    fixture.write("README.md", "# a\n");
    fixture.write(
        ".gitattributes",
        "locks/Cargo.lock linguist-generated=false\nweb/schema.json diffr-tags=schema,api\n",
    );
    fixture.user_attributes("user.txt diffr-tags=from-user\n");
    let base = fixture.commit();

    let lock = lock.replace("1.0.0", "1.1.0");
    fixture.write("Cargo.lock", &lock);
    fixture.write("locks/Cargo.lock", &lock);
    fixture.write(
        "api/service.go",
        &format!(
            "// Code generated by protoc-gen-go. DO NOT EDIT.\n{}",
            go.replace('1', "2")
        ),
    );
    fixture.write("src/lib.rs", "fn a() -> u32 {\n    2\n}\n");
    fixture.write("tests/check.py", "def test_a():\n    assert 2\n");
    fixture.write("web/schema.json", "{\"a\": 2}\n");
    fixture.write("user.txt", "two\n");
    fixture.write("README.md", "# b\n");
    let head = fixture.commit();

    let records = records(&fixture.run(&base, &head));
    assert_eq!(tags_of(&records, "Cargo.lock"), vec!["generated"]);
    assert_eq!(tags_of(&records, "locks/Cargo.lock"), Vec::<&str>::new());
    assert_eq!(tags_of(&records, "api/service.go"), vec!["generated"]);
    assert_eq!(tags_of(&records, "src/lib.rs"), Vec::<&str>::new());
    assert_eq!(tags_of(&records, "tests/check.py"), vec!["test"]);
    assert_eq!(tags_of(&records, "web/schema.json"), vec!["api", "schema"]);
    assert_eq!(tags_of(&records, "user.txt"), vec!["from-user"]);
    assert_eq!(tags_of(&records, "README.md"), vec!["docs"]);

    assert_eq!(fallback_of(&records, "Cargo.lock"), Some("generated"));
    assert_eq!(fallback_of(&records, "api/service.go"), Some("generated"));
    assert_ne!(fallback_of(&records, "locks/Cargo.lock"), Some("generated"));
    assert_eq!(fallback_of(&records, "src/lib.rs"), None);
}

/// The bundled classifier's path rules: Linguist's vendor and documentation
/// patterns, its generated-file names, and diffr's test paths.
#[test]
fn bundled_path_rules_tag_vendored_docs_test_and_generated_files() {
    let carries: &[(&str, &[&str])] = &[
        (
            "vendored",
            &[
                "node_modules/left-pad/index.js",
                "third_party/zlib/inflate.c",
                "static/jquery-3.7.1.min.js",
            ],
        ),
        ("docs", &["docs/cli.md", "README.md", "CHANGELOG.md"]),
    ];
    let lacks: &[(&str, &[&str])] = &[
        ("vendored", &["src/vendors.rs", "distribution/a.py"]),
        ("docs", &["src/docs/mod.rs", "src/readme_parser.rs"]),
        ("test", &["testing/helpers.rs", "src/testament.py"]),
        (
            "integration",
            &["src/plugin/tests/a.rs", "tests/integrations_test.py"],
        ),
    ];
    let exactly: &[(&str, &[&str])] = &[
        ("tests/streaming/check.py", &["test"]),
        ("src/App.test.tsx", &["test"]),
        ("src/review/tests.rs", &["test"]),
        ("tests/snapshots/Cargo.lock", &["generated", "test"]),
        ("crates/core/tests/login.rs", &["integration", "test"]),
        ("pkg/db/store_integration_test.go", &["integration", "test"]),
        ("web/e2e/checkout.spec.ts", &["e2e", "test"]),
        (
            "node_modules/x/package-lock.json",
            &["generated", "vendored"],
        ),
    ];
    let paths: std::collections::BTreeSet<&str> = carries
        .iter()
        .chain(lacks)
        .flat_map(|(_, paths)| paths.iter().copied())
        .chain(exactly.iter().map(|(path, _)| *path))
        .collect();
    let fixture = Fixture::new();
    for path in &paths {
        fixture.write(path, "one\n");
    }
    let base = fixture.commit();
    for path in &paths {
        fixture.write(path, "two\n");
    }
    let head = fixture.commit();
    let records = records(&fixture.run(&base, &head));
    for (tag, paths) in carries {
        for path in *paths {
            assert!(tags_of(&records, path).contains(tag), "{path} is {tag}");
        }
    }
    for (tag, paths) in lacks {
        for path in *paths {
            assert!(
                !tags_of(&records, path).contains(tag),
                "{path} is not {tag}"
            );
        }
    }
    for (path, expected) in exactly {
        assert_eq!(tags_of(&records, path), expected.to_vec(), "{path}");
    }
}

#[test]
fn test_content_tags_integration_and_end_to_end_files() {
    let files: &[(&str, &str, &[&str])] = &[
        (
            "store_test.go",
            "//go:build integration\n\npackage store\n",
            &["integration", "test"],
        ),
        (
            "tests/test_api.py",
            "import pytest\n\npytestmark = pytest.mark.e2e\n",
            &["e2e", "test"],
        ),
        (
            "src/checkout.spec.ts",
            "import { test } from '@playwright/test';\n",
            &["e2e", "test"],
        ),
        ("tests/test_unit.py", "import pytest\n", &["test"]),
    ];
    let fixture = Fixture::new();
    for (path, text, _) in files {
        fixture.write(path, text);
    }
    let base = fixture.commit();
    for (path, text, _) in files {
        fixture.write(path, &format!("{text}// changed\n"));
    }
    let head = fixture.commit();
    let records = records(&fixture.run(&base, &head));
    for (path, _, expected) in files {
        assert_eq!(tags_of(&records, path), expected.to_vec(), "{path}");
    }
}

/// Git attributes decide a tag outright, whatever the path rules said.
#[test]
fn linguist_attributes_set_or_clear_their_tags() {
    let fixture = Fixture::new();
    for path in [
        "Cargo.lock",
        "unset/Cargo.lock",
        "false/Cargo.lock",
        "src/schema.rs",
        "src/true.rs",
        "README.md",
    ] {
        fixture.write(path, "one\n");
    }
    fixture.write(
        ".gitattributes",
        "unset/Cargo.lock -linguist-generated\nfalse/Cargo.lock linguist-generated=false\nsrc/schema.rs linguist-generated\nsrc/true.rs linguist-generated=true\nREADME.md linguist-vendored -linguist-documentation\n",
    );
    let base = fixture.commit();
    for path in [
        "Cargo.lock",
        "unset/Cargo.lock",
        "false/Cargo.lock",
        "src/schema.rs",
        "src/true.rs",
        "README.md",
    ] {
        fixture.write(path, "two\n");
    }
    let head = fixture.commit();
    let records = records(&fixture.run(&base, &head));
    assert_eq!(tags_of(&records, "Cargo.lock"), vec!["generated"]);
    assert_eq!(tags_of(&records, "unset/Cargo.lock"), Vec::<&str>::new());
    assert_eq!(tags_of(&records, "false/Cargo.lock"), Vec::<&str>::new());
    assert_eq!(tags_of(&records, "src/schema.rs"), vec!["generated"]);
    assert_eq!(tags_of(&records, "src/true.rs"), vec!["generated"]);
    assert_eq!(tags_of(&records, "README.md"), vec!["vendored"]);
}

/// `diffr-tags` must be a comma-separated list of tag names.
#[test]
fn every_malformed_diffr_tags_value_is_an_error() {
    for attribute in [
        "diffr-tags",
        "diffr-tags=a,,b",
        "diffr-tags=Schema",
        "diffr-tags=-a",
    ] {
        let fixture = Fixture::new();
        fixture.write("web/a.json", "1\n");
        fixture.write(".gitattributes", &format!("web/a.json {attribute}\n"));
        let base = fixture.commit();
        fixture.write("web/a.json", "2\n");
        let head = fixture.commit();
        let output = fixture.run(&base, &head);
        assert_eq!(output.status.code(), Some(2), "{attribute}");
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            stderr.contains("web/a.json: diffr-tags"),
            "{attribute}: {stderr}"
        );
    }
}

/// A working-tree side names no stored blob: it carries git's null id, and the
/// classifier reads its content from the file system.
#[test]
fn working_tree_content_is_classified_from_the_file_system() {
    let fixture = Fixture::new();
    let go = "package api\n\nfunc A() int {\n\treturn 1\n}\n";
    fixture.write("api/service.go", go);
    let base = fixture.commit();
    fixture.write(
        "api/service.go",
        &format!("// Code generated by protoc-gen-go. DO NOT EDIT.\n{go}"),
    );
    let output = fixture.diff(&[&base]);
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let records = records(&output);
    assert_eq!(tags_of(&records, "api/service.go"), vec!["generated"]);
    let entry = records[0]["files"]
        .as_array()
        .unwrap()
        .iter()
        .find(|entry| path_of(&entry["file"]) == "api/service.go")
        .unwrap();
    assert_eq!(entry["file"]["rhs"]["oid"], "0".repeat(40));
    assert_ne!(entry["file"]["lhs"]["oid"], "0".repeat(40));
}

fn visibility_of<'a>(records: &'a [Value], path: &str) -> Option<&'a Value> {
    records
        .iter()
        .find(|record| record["type"] == "file" && path_of(&record["file"]) == path)
        .and_then(|record| {
            let diff = &record["diff"];
            diff["rhs"].get("root").or(diff["lhs"].get("root"))
        })
        .and_then(|root| root.get("visibility"))
}

/// By default the classifier hides generated and vendored files, and
/// deleted ones: each is diffed by line and shown behind its reason.
#[test]
fn hidden_files_are_diffed_by_line_and_shown_behind_their_reason() {
    let fixture = Fixture::new();
    let rust = |n: u32| format!("fn a() -> u32 {{\n    {n}\n}}\n");
    for path in ["vendor/lib/a.rs", "tests/a.rs", "src/a.rs", "src/gone.rs"] {
        fixture.write(path, &rust(1));
    }
    let base = fixture.commit();
    for path in ["vendor/lib/a.rs", "tests/a.rs", "src/a.rs"] {
        fixture.write(path, &rust(2));
    }
    fs::remove_file(fixture.dir.path().join("repo/src/gone.rs")).unwrap();
    let head = fixture.commit();

    let defaults = records(&fixture.run(&base, &head));
    let hidden = |label: &str| Some(serde_json::json!({"collapsed": true, "label": label}));
    assert_eq!(
        visibility_of(&defaults, "vendor/lib/a.rs").cloned(),
        hidden("Vendored file · hidden by default")
    );
    assert_eq!(fallback_of(&defaults, "vendor/lib/a.rs"), Some("hidden"));
    assert_eq!(visibility_of(&defaults, "tests/a.rs"), None);
    assert_eq!(
        visibility_of(&defaults, "src/gone.rs").cloned(),
        hidden("Deleted file · hidden by default")
    );
    assert_eq!(visibility_of(&defaults, "src/a.rs"), None);
    assert_eq!(fallback_of(&defaults, "src/a.rs"), None);

    fixture.config("[plugins.classify.bundled]\nhide = []\nhide_deleted = false\n");
    let shown = records(&fixture.run(&base, &head));
    for path in ["vendor/lib/a.rs", "tests/a.rs", "src/gone.rs"] {
        assert_eq!(visibility_of(&shown, path), None, "{path}");
    }
    assert_eq!(
        fallback_of(&shown, "vendor/lib/a.rs"),
        None,
        "a shown vendored file is diffed structurally"
    );
}
