; inherits: builtin:core/queries/ada/folds.scm
([
  (accept_statement)
  (assignment_statement)
  (block_statement)
  (case_expression)
  (case_statement)
  (entry_barrier)
  (exception_handler)
  (function_call)
  (if_expression)
  (label)
  (loop_label)
  (loop_statement)
  (package_body)
  (package_declaration)
  (raise_expression)
  (raise_statement)
  (record_type_definition)
  (selective_accept)
  (string_literal)
] @fold (#set! tag "context:scope"))
([
  (case_expression)
  (case_statement)
  (if_expression)
  (if_statement)
] @fold (#set! tag "context:branches"))
([
  (case_statement)
  (exception_handler)
] @fold (#set! tag "context:clause"))

((if_statement statements: (_) @fold @fold.indent statements: (_)* @fold) (#set! tag "context:body"))
((if_statement else_statements: (_) @fold @fold.indent else_statements: (_)* @fold) (#set! tag "context:body"))
((if_statement "else" @fold) (#set! tag "context:relevant"))
((if_statement "elsif" @fold) (#set! tag "context:relevant"))
((handled_sequence_of_statements . (_) @fold.indent) @fold (#set! tag "context:body"))

((subprogram_body) @fold (#set! tag "context:scope"))
