; inherits: builtin:core/queries/apex/folds.scm
((argument_list "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
((block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((class_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((constructor_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((enum_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((interface_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((switch_block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
([
  (assignment_expression)
  (class_declaration)
  (constructor_declaration)
  (do_statement)
  (enhanced_for_statement)
  (enum_declaration)
  (for_statement)
  (function_expression)
  (if_statement)
  (interface_declaration)
  (local_variable_declaration)
  (method_declaration)
  (return_statement)
  (static_initializer)
  (string_literal)
  (switch_expression)
  (throw_statement)
  (try_statement)
  (when_expression)
  (while_statement)
] @fold (#set! tag "context:scope"))
([
  (if_statement)
  (switch_expression)
  (try_statement)
  (when_expression)
] @fold (#set! tag "context:branches"))

((expression_statement) @fold (#set! tag "context:scope"))
