; inherits: builtin:core/queries/c/folds.scm
((argument_list "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
((compound_statement "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((declaration_list "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((field_declaration_list "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((initializer_list "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
([
  (assignment_expression)
  (case_statement)
  (conditional_expression)
  (declaration)
  (do_statement)
  (else_clause)
  (for_statement)
  (function_definition)
  (if_statement)
  (labeled_statement)
  (preproc_call)
  (preproc_else)
  (preproc_function_def)
  (preproc_if)
  (preproc_ifdef)
  (return_statement)
  (string_literal)
  (struct_specifier)
  (switch_statement)
  (union_specifier)
  (while_statement)
] @fold (#set! tag "context:scope"))
([
  (case_statement)
  (if_statement)
  (preproc_else)
  (preproc_if)
  (preproc_ifdef)
  (switch_statement)
] @fold (#set! tag "context:branches"))
([
  (case_statement)
  (else_clause)
  (preproc_else)
] @fold (#set! tag "context:clause"))

((expression_statement) @fold (#set! tag "context:scope"))
