; inherits: builtin:core/queries/cplusplus/folds.scm
((argument_list "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
((compound_statement "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((declaration_list "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((field_declaration_list "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((initializer_list "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
([
  (assignment_expression)
  (case_statement)
  (catch_clause)
  (class_specifier)
  (co_yield_statement)
  (conditional_expression)
  (declaration)
  (do_statement)
  (else_clause)
  (field_initializer)
  (field_initializer_list)
  (for_statement)
  (function_definition)
  (if_statement)
  (labeled_statement)
  (lambda_expression)
  (namespace_definition)
  (preproc_call)
  (preproc_else)
  (preproc_function_def)
  (preproc_if)
  (preproc_ifdef)
  (raw_string_literal)
  (return_statement)
  (static_assert_declaration)
  (string_literal)
  (struct_specifier)
  (switch_statement)
  (throw_statement)
  (try_statement)
  (union_specifier)
  (using_declaration)
  (while_statement)
] @fold (#set! tag "context:scope"))
([
  (case_statement)
  (if_statement)
  (preproc_else)
  (preproc_if)
  (preproc_ifdef)
  (switch_statement)
  (try_statement)
] @fold (#set! tag "context:branches"))
([
  (case_statement)
  (catch_clause)
  (else_clause)
  (preproc_else)
] @fold (#set! tag "context:clause"))

((function_definition (field_initializer_list) @fold) (#set! tag "context:relevant"))
((expression_statement) @fold (#set! tag "context:scope"))
(((access_specifier) @fold . ":" @fold) (#set! tag "context:scope"))
