; inherits: builtin:core/queries/csharp/folds.scm
((argument_list "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
((block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((declaration_list "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((switch_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
([
  (accessor_declaration)
  (accessor_list)
  (as_expression)
  (assignment_expression)
  (await_expression)
  (catch_clause)
  (checked_statement)
  (class_declaration)
  (conditional_expression)
  (constructor_declaration)
  (destructor_declaration)
  (do_statement)
  (enum_declaration)
  (file_scoped_namespace_declaration)
  (finally_clause)
  (for_statement)
  (foreach_statement)
  (from_clause)
  (if_statement)
  (initializer_expression)
  (interface_declaration)
  (join_clause)
  (labeled_statement)
  (lambda_expression)
  (local_declaration_statement)
  (lock_statement)
  (method_declaration)
  (namespace_declaration)
  (preproc_else)
  (preproc_if)
  (property_declaration)
  (query_expression)
  (raw_string_literal)
  (record_declaration)
  (return_statement)
  (select_clause)
  (string_literal)
  (string_literal_content)
  (struct_declaration)
  (switch_expression)
  (switch_expression_arm)
  (switch_section)
  (switch_statement)
  (throw_expression)
  (throw_statement)
  (try_statement)
  (tuple_expression)
  (unsafe_statement)
  (using_directive)
  (using_statement)
  (verbatim_string_literal)
  (while_statement)
  (with_expression)
  (yield_statement)
] @fold (#set! tag "context:scope"))
([
  (if_statement)
  (preproc_else)
  (preproc_if)
  (switch_expression)
  (switch_statement)
  (try_statement)
] @fold (#set! tag "context:branches"))
([
  (catch_clause)
  (finally_clause)
  (preproc_else)
] @fold (#set! tag "context:clause"))

((accessor_list (accessor_declaration) @fold) (#set! tag "context:relevant"))

((preproc_nullable) @fold (#set! tag "context:scope"))

([
  (expression_statement)
  (field_declaration)
] @fold (#set! tag "context:scope"))
