; inherits: builtin:core/queries/dart/folds.scm
((arguments "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
((block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((class_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((enum_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((extension_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((switch_block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
([
  (assert_statement)
  (assertion)
  (assignment_expression)
  (catch_clause)
  (class_definition)
  (conditional_expression)
  (do_statement)
  (enum_declaration)
  (field_initializer)
  (finally_clause)
  (for_statement)
  (function_expression)
  (if_statement)
  (label)
  (lambda_expression)
  (local_variable_declaration)
  (pair)
  (rethrow_expression)
  (return_statement)
  (string_literal)
  (switch_expression)
  (switch_statement)
  (throw_expression)
  (try_statement)
  (while_statement)
  (yield_each_statement)
  (yield_statement)
] @fold (#set! tag "context:scope"))
([
  (if_statement)
  (switch_expression)
  (switch_statement)
  (try_statement)
] @fold (#set! tag "context:branches"))
([
  (catch_clause)
  (finally_clause)
] @fold (#set! tag "context:clause"))

((expression_statement) @fold (#set! tag "context:scope"))
(((function_signature) @fold . (function_body) @fold) (#set! tag "context:scope"))
(((method_signature) @fold . (function_body) @fold) (#set! tag "context:scope"))
(((constructor_signature) @fold . (initializers)? . (function_body) @fold) (#set! tag "context:scope"))
