; inherits: builtin:core/queries/dockerfile/folds.scm
([
  (add_instruction)
  (arg_instruction)
  (cmd_instruction)
  (copy_instruction)
  (cross_build_instruction)
  (entrypoint_instruction)
  (env_instruction)
  (expose_instruction)
  (from_instruction)
  (healthcheck_instruction)
  (heredoc_block)
  (label_instruction)
  (maintainer_instruction)
  (onbuild_instruction)
  (run_instruction)
  (shell_instruction)
  (stopsignal_instruction)
  (user_instruction)
  (volume_instruction)
  (workdir_instruction)
] @fold (#set! tag "context:scope"))

