; inherits: builtin:core/queries/fortran/folds.scm
((argument_list "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
([
  (array_literal)
  (assignment)
  (assignment_statement)
  (call_expression)
  (case_statement)
  (conditional_expression)
  (do_statement)
  (elseif_clause)
  (function)
  (module)
  (preproc_call)
  (preproc_function_def)
  (program)
  (string_literal)
  (subroutine)
  (variable_declaration)
  (while_statement)
] @fold (#set! tag "context:scope"))
([
  (case_statement)
  (elseif_clause)
  (if_statement)
] @fold (#set! tag "context:branches"))
([
  (case_statement)
  (elseif_clause)
] @fold (#set! tag "context:clause"))

((else_clause "else" @fold.open . (_) @fold.indent) @fold (#set! tag "context:body"))
((if_statement (parenthesized_expression) @fold "then" @fold.open . (_) @fold.indent (end_if_statement) @fold @fold.close) (#set! tag "context:body"))
((if_statement (parenthesized_expression) @fold "then" @fold.open . (_) @fold.indent (end_if_statement) @fold @fold.close) (#set! tag "context:branches"))
