; inherits: builtin:core/queries/java/folds.scm
((annotation_type_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((argument_list "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
((block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((class_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((constructor_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((enum_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((interface_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((module_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((record_pattern_body "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
((switch_block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
([
  (assert_statement)
  (assignment_expression)
  (catch_clause)
  (class_declaration)
  (constructor_declaration)
  (do_statement)
  (enhanced_for_statement)
  (enum_declaration)
  (finally_clause)
  (for_statement)
  (if_statement)
  (import_declaration)
  (interface_declaration)
  (labeled_statement)
  (lambda_expression)
  (local_variable_declaration)
  (method_declaration)
  (module_declaration)
  (package_declaration)
  (record_declaration)
  (return_statement)
  (static_initializer)
  (string_literal)
  (switch_expression)
  (synchronized_statement)
  (throw_statement)
  (try_statement)
  (while_statement)
  (yield_statement)
] @fold (#set! tag "context:scope"))
([
  (if_statement)
  (switch_expression)
  (try_statement)
] @fold (#set! tag "context:branches"))
([
  (catch_clause)
  (finally_clause)
] @fold (#set! tag "context:clause"))

((expression_statement) @fold (#set! tag "context:scope"))
