; inherits: builtin:core/queries/julia/folds.scm
((argument_list "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
((compound_statement "begin" @fold.open . (_) @fold.indent "end" @fold.close) @fold (#set! tag "context:body"))
([
  (assignment)
  (call_expression)
  (catch_clause)
  (comprehension_expression)
  (finally_clause)
  (for_statement)
  (function_definition)
  (macro_definition)
  (module_definition)
  (return_statement)
  (string_literal)
  (try_statement)
  (tuple_expression)
  (using_statement)
  (while_statement)
] @fold (#set! tag "context:scope"))
([
  (if_statement)
  (try_statement)
] @fold (#set! tag "context:branches"))
([
  (catch_clause)
  (finally_clause)
] @fold (#set! tag "context:clause"))

((comprehension_expression (for_clause) @fold) (#set! tag "context:relevant"))
((comprehension_expression (if_clause) @fold) (#set! tag "context:relevant"))
((else_clause "else" @fold.open . (_) @fold.indent) @fold (#set! tag "context:body"))
((elseif_clause "elseif" @fold.open . (_) @fold.indent) @fold (#set! tag "context:body"))
((if_statement "if" @fold condition: (_) @fold.open . (_) @fold.indent "end" @fold @fold.close) (#set! tag "context:body"))
((if_statement "if" @fold condition: (_) @fold.open . (_) @fold.indent "end" @fold @fold.close) (#set! tag "context:branches"))
