; inherits: builtin:core/queries/kotlin/folds.scm
((class_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((control_structure_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((enum_class_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((function_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((value_arguments "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
([
  (anonymous_function)
  (anonymous_initializer)
  (as_expression)
  (assignment)
  (class_declaration)
  (do_while_statement)
  (for_statement)
  (function_declaration)
  (if_expression)
  (import_header)
  (lambda_literal)
  (property_declaration)
  (string_literal)
  (try_expression)
  (variable_declaration)
  (when_entry)
  (when_expression)
  (while_statement)
] @fold (#set! tag "context:scope"))
([
  (if_expression)
  (try_expression)
  (when_expression)
] @fold (#set! tag "context:branches"))
((when_entry) @fold (#set! tag "context:clause"))

((statements . (_) @fold.indent) @fold (#set! tag "context:body"))
((catch_block) @fold (#set! tag "context:scope"))
((catch_block) @fold (#set! tag "context:clause"))
((finally_block) @fold (#set! tag "context:scope"))
((finally_block) @fold (#set! tag "context:clause"))
((statements (call_expression) @fold) (#set! tag "context:scope"))
