; inherits: builtin:core/queries/lua/folds.scm
((arguments "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
([
  (assignment_statement)
  (do_statement)
  (else_statement)
  (elseif_statement)
  (for_statement)
  (function_call)
  (function_declaration)
  (function_definition)
  (if_statement)
  (repeat_statement)
  (return_statement)
  (string)
  (variable_declaration)
  (while_statement)
] @fold (#set! tag "context:scope"))
((if_statement) @fold (#set! tag "context:branches"))
([
  (else_statement)
  (elseif_statement)
] @fold (#set! tag "context:clause"))

((block . (_) @fold.indent) @fold (#set! tag "context:body"))
