; inherits: builtin:core/queries/objc/folds.scm
((argument_list "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
((compound_statement "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((declaration_list "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((field_declaration_list "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((initializer_list "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((ms_asm_block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
([
  (array_literal)
  (assignment_expression)
  (call_expression)
  (case_statement)
  (catch_clause)
  (class_declaration)
  (class_implementation)
  (conditional_expression)
  (dictionary_literal)
  (do_statement)
  (else_clause)
  (finally_clause)
  (for_statement)
  (function_definition)
  (if_statement)
  (labeled_statement)
  (method_declaration)
  (method_definition)
  (preproc_call)
  (preproc_else)
  (preproc_function_def)
  (preproc_if)
  (preproc_ifdef)
  (property_declaration)
  (protocol_declaration)
  (return_statement)
  (string_literal)
  (struct_declaration)
  (struct_specifier)
  (switch_statement)
  (synchronized_statement)
  (throw_statement)
  (try_statement)
  (union_specifier)
  (while_statement)
] @fold (#set! tag "context:scope"))
([
  (case_statement)
  (if_statement)
  (preproc_else)
  (preproc_if)
  (preproc_ifdef)
  (switch_statement)
  (try_statement)
] @fold (#set! tag "context:branches"))
([
  (case_statement)
  (catch_clause)
  (else_clause)
  (finally_clause)
  (preproc_else)
] @fold (#set! tag "context:clause"))

