; inherits: builtin:core/queries/php/folds.scm
((arguments "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
((compound_statement "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((declaration_list "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((match_block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((switch_block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
([
  (anonymous_function)
  (array_creation_expression)
  (arrow_function)
  (assignment_expression)
  (case_statement)
  (catch_clause)
  (class_declaration)
  (conditional_expression)
  (do_statement)
  (else_clause)
  (else_if_clause)
  (enum_declaration)
  (finally_clause)
  (for_statement)
  (foreach_statement)
  (function_call_expression)
  (function_definition)
  (if_statement)
  (interface_declaration)
  (match_expression)
  (member_call_expression)
  (method_declaration)
  (namespace_definition)
  (pair)
  (property_declaration)
  (return_statement)
  (string)
  (switch_statement)
  (throw_expression)
  (try_statement)
  (while_statement)
  (yield_expression)
] @fold (#set! tag "context:scope"))
([
  (case_statement)
  (else_if_clause)
  (if_statement)
  (match_expression)
  (switch_statement)
  (try_statement)
] @fold (#set! tag "context:branches"))
([
  (case_statement)
  (catch_clause)
  (else_clause)
  (else_if_clause)
  (finally_clause)
] @fold (#set! tag "context:clause"))

