; inherits: builtin:core/queries/qml/folds.scm
((arguments "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
((array "[" @fold.open . (_) @fold.indent "]" @fold.close) @fold (#set! tag "context:body"))
((class_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((enum_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((object "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((statement_block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((switch_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
([
  (arrow_function)
  (assignment_expression)
  (catch_clause)
  (class_declaration)
  (class_static_block)
  (do_statement)
  (else_clause)
  (enum_declaration)
  (finally_clause)
  (for_in_statement)
  (for_statement)
  (function_declaration)
  (function_expression)
  (generator_function)
  (generator_function_declaration)
  (if_statement)
  (interface_declaration)
  (internal_module)
  (labeled_statement)
  (lexical_declaration)
  (method_definition)
  (module)
  (pair)
  (return_statement)
  (satisfies_expression)
  (string)
  (switch_case)
  (switch_statement)
  (template_string)
  (throw_statement)
  (try_statement)
  (type_assertion)
  (ui_binding)
  (ui_inline_component)
  (ui_object_definition)
  (ui_object_definition_binding)
  (ui_object_initializer)
  (ui_property)
  (variable_declaration)
  (while_statement)
  (with_statement)
  (yield_expression)
] @fold (#set! tag "context:scope"))
([
  (if_statement)
  (switch_statement)
  (try_statement)
] @fold (#set! tag "context:branches"))
([
  (catch_clause)
  (else_clause)
  (finally_clause)
  (switch_case)
] @fold (#set! tag "context:clause"))

((expression_statement) @fold (#set! tag "context:scope"))
