; inherits: builtin:core/queries/scala/folds.scm
((arguments "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
((block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((case_block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((enum_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((template_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((with_template_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
([
  (assignment_expression)
  (case_clause)
  (catch_clause)
  (class_definition)
  (finally_clause)
  (for_expression)
  (function_declaration)
  (function_definition)
  (if_expression)
  (lambda_expression)
  (match_expression)
  (package_clause)
  (return_expression)
  (string)
  (throw_expression)
  (try_expression)
  (tuple_expression)
  (val_definition)
  (var_definition)
  (while_expression)
] @fold (#set! tag "context:scope"))
([
  (if_expression)
  (match_expression)
  (try_expression)
] @fold (#set! tag "context:branches"))
([
  (case_clause)
  (catch_clause)
  (finally_clause)
] @fold (#set! tag "context:clause"))

((block (call_expression) @fold) (#set! tag "context:scope"))
