; inherits: builtin:core/queries/solidity/folds.scm
((contract_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((enum_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((function_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((struct_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((yul_block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
([
  (assignment_expression)
  (catch_clause)
  (contract_declaration)
  (do_while_statement)
  (enum_declaration)
  (for_statement)
  (function_definition)
  (if_statement)
  (interface_declaration)
  (return_statement)
  (string)
  (string_literal)
  (struct_declaration)
  (try_statement)
  (tuple_expression)
  (variable_declaration)
  (while_statement)
] @fold (#set! tag "context:scope"))
([
  (if_statement)
  (try_statement)
] @fold (#set! tag "context:branches"))
((catch_clause) @fold (#set! tag "context:clause"))

((expression_statement) @fold (#set! tag "context:scope"))
