; inherits: builtin:core/queries/sql/folds.scm
((array "[" @fold.open . (_) @fold.indent "]" @fold.close) @fold (#set! tag "context:body"))
((list "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
([
  (assignment)
  (create_function)
  (from)
  (function_declaration)
  (function_language)
  (function_security)
  (function_volatility)
  (group_by)
  (join)
  (order_by)
  (select)
  (statement)
  (transaction)
  (where)
] @fold (#set! tag "context:scope"))

((statement (from) @fold) (#set! tag "context:relevant"))
((statement (where) @fold) (#set! tag "context:relevant"))
((statement (group_by) @fold) (#set! tag "context:relevant"))
((statement (order_by) @fold) (#set! tag "context:relevant"))
((statement (join) @fold) (#set! tag "context:relevant"))
((select_expression . (_) @fold.indent) @fold (#set! tag "context:body"))
((select) @fold (#set! tag "context:open-ended"))

; Routine attributes may follow the body, beyond ordinary line context.
((create_function [(function_language) (function_security) (function_volatility)
 (function_leakproof) (function_safety) (function_strictness) (function_cost)
 (function_rows) (function_support)] @fold) (#set! tag "context:relevant"))
([(function_body (keyword_begin) @fold.open . (_) @fold.indent (keyword_end) @fold.close)
  (function_body (keyword_as) (dollar_quote) @fold.open . [(statement) (keyword_return)] @fold.indent (dollar_quote) @fold.close)] @fold (#set! tag "context:body"))
((create_function (function_body (keyword_end) @fold . ";" @fold . (dollar_quote) @fold)) (#set! tag "context:relevant"))
