; inherits: builtin:core/queries/swift/folds.scm
((class_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((deprecated_operator_declaration_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((enum_class_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((function_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((protocol_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((value_arguments "[" @fold.open . (_) @fold.indent "]" @fold.close) @fold (#set! tag "context:body"))
((willset_didset_block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
([
  (array_literal)
  (assignment)
  (class_declaration)
  (computed_getter)
  (computed_setter)
  (deinit_declaration)
  (dictionary_literal)
  (function_declaration)
  (import_declaration)
  (init_declaration)
  (lambda_literal)
  (macro_definition)
  (macro_invocation)
  (multi_line_string_literal)
  (property_declaration)
  (protocol_declaration)
  (raw_string_literal)
  (switch_statement)
  (tuple_expression)
] @fold (#set! tag "context:scope"))
([
  (if_statement)
  (switch_statement)
] @fold (#set! tag "context:branches"))

((statements . (_) @fold.indent) @fold (#set! tag "context:body"))

((function_declaration body: (function_body (statements (control_transfer_statement) @fold (#match? @fold "^defer\\b")))) (#set! tag "context:relevant"))
((function_declaration body: (function_body (statements (call_expression (simple_identifier) @_defer) @fold (#eq? @_defer "defer")))) (#set! tag "context:relevant"))
((statements (call_expression) @fold) (#set! tag "context:scope"))
((statements (try_expression) @fold) (#set! tag "context:scope"))
((statements (await_expression) @fold) (#set! tag "context:scope"))
((statements (as_expression) @fold) (#set! tag "context:scope"))
