; inherits: builtin:core/queries/verilog/folds.scm
((constraint_block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((cross_body "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((generate_block "begin" @fold.open . (_) @fold.indent "end" @fold.close) @fold (#set! tag "context:body"))
((seq_block "begin" @fold.open . (_) @fold.indent "end" @fold.close) @fold (#set! tag "context:body"))
([
  (always_construct)
  (case_expression)
  (case_statement)
  (class_declaration)
  (clocking_declaration)
  (conditional_expression)
  (event_control)
  (function_declaration)
  (interface_declaration)
  (let_declaration)
  (loop_statement)
  (module_declaration)
  (package_declaration)
  (property_declaration)
  (string_literal)
  (task_declaration)
  (type_declaration)
] @fold (#set! tag "context:scope"))
([
  (case_expression)
  (case_statement)
] @fold (#set! tag "context:branches"))
((case_statement) @fold (#set! tag "context:clause"))

