; inherits: builtin:core/queries/vhdl/folds.scm
([
  (case_expression)
  (case_statement)
  (conditional_expression)
  (function_call)
  (if_statement)
  (interface_declaration)
  (loop_statement)
  (package_declaration)
  (process_head)
  (process_statement)
  (return_statement)
  (string_literal)
  (type_declaration)
  (variable_declaration)
  (when_expression)
  (with_expression)
] @fold (#set! tag "context:scope"))
([
  (case_expression)
  (case_statement)
  (if_statement)
  (when_expression)
] @fold (#set! tag "context:branches"))
((case_statement) @fold (#set! tag "context:clause"))

((sequential_block . (_) @fold.indent) @fold (#set! tag "context:body"))
((concurrent_block . (_) @fold.indent) @fold (#set! tag "context:body"))
((architecture_definition) @fold (#set! tag "context:scope"))
