; inherits: builtin:core/queries/zig/folds.scm
((arguments "(" @fold.open . (_) @fold.indent ")" @fold.close) @fold (#set! tag "context:body"))
((block "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
((initializer_list "{" @fold.open . (_) @fold.indent "}" @fold.close) @fold (#set! tag "context:body"))
([
  (assignment_expression)
  (block_label)
  (call_expression)
  (comptime_expression)
  (comptime_statement)
  (enum_declaration)
  (field_initializer)
  (for_expression)
  (for_statement)
  (function_declaration)
  (if_expression)
  (if_statement)
  (labeled_statement)
  (multiline_string)
  (return_expression)
  (string)
  (struct_declaration)
  (switch_case)
  (switch_expression)
  (try_expression)
  (union_declaration)
  (variable_declaration)
  (while_expression)
  (while_statement)
] @fold (#set! tag "context:scope"))
([
  (if_expression)
  (if_statement)
  (switch_expression)
] @fold (#set! tag "context:branches"))
((switch_case) @fold (#set! tag "context:clause"))

((function_declaration body: (block (defer_statement) @fold)) (#set! tag "context:relevant"))
((function_declaration body: (block (errdefer_statement) @fold)) (#set! tag "context:relevant"))
